name: SpawnProtect
version: 0.10.5
description: Protects the spawn area
author: acomputerdog
main: net.acomputerdog.spawnprotect.PluginSpawnProtect
load: STARTUP

permissions:
  spawnprotect.bypass:
    description: Bypass spawn protection
    default: op